all: main
main:
	g++ -o main main.cc algorithms.cc algorithms.h compare_algorithms.cc compare_algorithms.h edp_test.cc index.cc index.h partition.cc partition.h vertex.cc vertex.h -std=c++11 -O3
    
clean:
	rm -f main.o main
